minerals/urls.py
from django.conf.urls import url

from . import views

app_name = 'minerals'

urlpatterns = [
    url(r'(?P<pk>\d+)/$', views.mineral_detail, name='detail'),
    url(r'(?P<letter>[a-zA-Z]+)$', views.mineral_list_letter_filter,
        name='letter_filter'),
    url(r'$', views.search_minerals, name='search_minerals'),    
]

minerals_site/urls.py
from . import views

from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    url(r'^minerals/', include('minerals.urls', namespace='minerals')),
    url(r'^admin/', admin.site.urls),
    url(r'^', views.mineral_list_inital_filter),    
    ] 

urlpatterns += staticfiles_urlpatterns()

minerals/models.py
''' The Mineral Catalog uses a single Model '''

from django.db import models


class Mineral(models.Model):
    ''' The Mineral class / table '''
    name = models.CharField(max_length=255)
    img_filename = models.CharField(max_length=255)
    img_caption = models.TextField(max_length=255)
    category = models.CharField(max_length=255)
    formula = models.CharField(max_length=255)
    strunz_classification = models.CharField(max_length=255)
    crystal_system = models.CharField(max_length=255)
    unit_cell = models.CharField(max_length=255)
    color = models.CharField(max_length=255)
    crystal_symmetry = models.CharField(max_length=255)
    cleavage = models.CharField(max_length=255)
    mohs_hardness = models.CharField(max_length=255)
    luster = models.CharField(max_length=255)
    streak = models.CharField(max_length=255)
    diaphaneity = models.CharField(max_length=255)
    optical_properties = models.CharField(max_length=255)
    refractive_index = models.CharField(max_length=255, blank=True, default='')
    crystal_habit = models.CharField(max_length=255, blank=True, default='')
    specific_gravity = models.CharField(max_length=255, blank=True, default='')
    group = models.CharField(max_length=255, blank=True, default='')
 
    class Meta:
        ''' order the mineral claass based on the name '''
        ordering = ['name']

    def __str__(self):
        return self.name

minerals/forms.py
''' cutsom forms for the accounts application '''

from django import forms

GROUP_CHOICES = [(1, 'Silicates'), (2, 'Oxides'), (3, 'Sulfates')]
                 

class SearchForm(forms.Form):
    ''' search form for the minerals catalog '''
    search_query = forms.CharField(label="Enter search criteria", max_length=30,
                                   widget=forms.TextInput(
                                       {'class': 'form-control'}
                                  ))

class FilterForm(forms.Form):
    ''' filter by groups form '''
    # group_choice_field = forms.ChoiceField(choices=['test'])
    group_choice_field = forms.ChoiceField(label="Choose a group",
                                           choices=GROUP_CHOICES,
                                           widget=forms.Select(
                                           attrs={'class': 'form-control'}))
                                                  
                                           

minerals/views.py
import random

from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from .forms import SearchForm
from .models import Mineral

def mineral_list_letter_filter(request, letter):
    ''' create the list view of the mineral by search query'''
    if letter != 'ALL':
         minerals = Mineral.objects.filter(name__startswith=letter)
    else:
        minerals = Mineral.objects.all()
    random_mineral = random.choice(minerals)
    return render(request, 'minerals/index.html',
        {'minerals': minerals, 'random_mineral' : random_mineral})
                            
def mineral_detail(request, pk):
    ''' create the detail view of a single mineral '''
    minerals = Mineral.objects.all()
    random_mineral = random.choice(minerals)
    mineral = get_object_or_404(Mineral, pk=pk)
    return render(request, 'minerals/detail.html',
                  {'mineral' : mineral, 'random_mineral' : random_mineral})

def search_minerals(request):
    ''' create the search view  '''
    message = ''
    letter_q = 'A'

    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            data = request.POST.get('search_query')
            if data:
                mineral = Mineral.objects.filter(name=data)
                if not mineral.count():
                    message = 'Mineral matching query does not exist'
                    messages.info(request, message, fail_silently=True)
                else:
                    minerals = Mineral.objects.all()
                    random_mineral = random.choice(minerals)
                    return render(request, 'minerals/detail.html',
                                  {'mineral' : mineral[0],
                                   'messages' : messages,
                                   'random_mineral' : random_mineral})
            else:
                message = 'You did not enter a serach criteria'
            messages.info(request, message, fail_silently=True)
            return HttpResponseRedirect(
                reverse('minerals:letter_filter',
                        args=letter_q))
    else:
        form = SearchForm()
        minerals = Mineral.objects.all()
        random_mineral = random.choice(minerals)
        return render(request, 'minerals/index.html',
                      {'minerals' : minerals,
                       'random_mineral' : random_mineral,
                       'messages' : messages,
                       'form': form})

minerals_site/views.py
from django.shortcuts import render

from minerals.models import Mineral

def mineral_list_inital_filter(request):
    """Returns a list of all minerals that begin with letter."""
    all_minerals = Mineral.objects.all()
    minerals_by_letter = Mineral.objects.filter(name__istartswith='A')
    return render(request, 'home.html', {'minerals': minerals_by_letter})
       

minerals/templates/minerals/detail.html
{% extends 'layout.html' %}
{% load static from staticfiles %}
{% block content %}

      <div class="grid-100 mineral__container">
        <h1 class="mineral__name">{{ mineral.name }}</h1>
        <div class="mineral__image-bg">
          <img class="mineral__image" src="{% static 'images' %}/{{ mineral.name }}.jpg">
          <p class="mineral__caption">{{ mineral.img_caption}}</p>
        </div>
        <div class="mineral__table-container">
          <table class="mineral__table">
            <tr>
              <td class="mineral__category">mineral category</td>
              <td>{{ mineral.category|title }}</td>
            </tr>
            <tr>
              <td class="mineral__category">mineral formula</td>
              <td class="mineral__formula">{{ mineral.formula }}</td>
            </tr>
            <tr>
              <td class="mineral__category">Strunz Classification</td>
              <td>{{ mineral.strunz_classification }}</td>
            </tr>
            <tr>
              <td class="mineral__category">Unit Cell</td>
              <td>{{ mineral.unit_cell }}</td>
            </tr>
            <tr>
              <td class="mineral__category">Color</td>
              <td>{{ mineral.color }}</td>
            </tr>
            <tr>
              <td class="mineral__category">Crystal Habit</td>
              <td>{{ mineral.crystal_habit }}</td>
            </tr>
            <tr>
              <td class="mineral__category">Mohs Scale Hardness</td>
              <td>{{ mineral.mohs_hardness }}</td>
            </tr>
          </table>
        </div>
      </div>
    </div>
    <div class="minerals__random">
      <a class="minerals__anchor" href="{% url 'minerals:detail' pk=random_mineral.pk %}">Show random mineral</a>
    </div>
{% endblock %}

minerals/templates/minerals/index.html
{% extends 'layout.html' %}
{% load static from staticfiles %}


{% block content %}
  
       <div class="grid-100">
          <ul class="minerals__container">
            {% for mineral in minerals %}
                <li class="minerals__item">
                  <a class="minerals__anchor" href="{% url 'minerals:detail' pk=mineral.pk %}">{{ mineral.name }}</a>
                </li>
            {% endfor %}
          </ul>
        </div>
  
</div>
  <div class="minerals__random">
    <a class="minerals__anchor" href="{% url 'minerals:detail' pk=random_mineral.pk %}">Show Random Mineral</a>
  </div>
{% endblock %}

templates/home.html
{% extends 'layout.html' %}

{% block content %}
    
  <div class="grid-100">
    <ul class="minerals__container">
      {% for mineral in minerals %}
        <li class="minerals__item">
          <a class="minerals__anchor" href="{% url 'minerals:detail' pk=mineral.pk %}">{{ mineral.name }}</a>
        </li>
        {% endfor %}
    </ul>
  </div>
 
{% endblock %}

templates/layout.html
{% load static from staticfiles %}
{% load minerals_tags %}
{% alphabet_list as letters %}

<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Macky's Minerals: A magnificant catalog of minerals</title>
        <meta name="description" content="">
        <meta name="author" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Cousine' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/global.css' %}">
    </head>

    <body>
    <div class="bounds">
        <div class="grid-100">
            <a href="{% url 'minerals:letter_filter' letter='ALL' %}">
                <svg class="logo" viewBox="0 0 127.6 84.8" preserveAspectRation="xMinYMin meet">
                <polygon points="42.7,84.8 49.6,79.4 40,62.5 51.2,43.5 51.2,43.5 25,0 0,55.6 "/>
                <polygon class="logo--middle" points="52.9,79.5 52.9,79.5 84.8,80.1 59.7,35 43.3,62.4 "/>
                <polygon points="127.6,61.4 127.6,61.4 110.3,13.5 110.3,13.5 70.3,48.1 70.3,48.1 88.3,80.5 95.3,81.4 95.3,81.4 "/>
                </svg>
                <h1 class="logo__name text-centered">Macky's Minerals</h1>
             </a>
             <h4 class="text-centered">They're not rocks</h4>
        </div> 

        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <ul class="alphabet">
                        {% for letter in letters %}
                            <li><a href="{% url 'minerals:letter_filter' letter=letter %}">{{ letter }}</a></li>
                        {% endfor %}    
                    </ul>
                </div>    
            </div>    
         </div>
        
         <div class="container-fluid">
            <p></p> 
            <div class="row"> 
                <div class="col-sm-2"></div>
                    <div class="col-sm-4">
                        <form class="form" method="POST" action="{% url 'minerals:search_minerals' %}">
                            <div class="form-group mb-2">
                                {% csrf_token %}
                                {% search_form %}
                                <div> 
                                    <input type="submit" class="btn btn-secondary mb-2" value="Search">
                                </div>    
                            </div>
                        </form>
                    </div>  
                    <div class="col-sm-4">  
                        <form class="form" method="POST" action="#">
                            {% csrf_token %}
                            {% filter_form %}
                        </form>
                    </div>
                <div class="col-sm-2"></div>
            </div> 
        </div>       

        {% block content %}{% endblock %}

        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>    
    </body>
</html>